name: Java Tests

on:
  push:
    branches:
       - "main"
       - "dev/**"
       - "codex/**"
  pull_request:
    branches: ["main", "dev/**", "codex/**"]

jobs:
  java-unit-tests:
    name: Java Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'
      - name: "Compile"
        run: ./mvn_cmd clean compile test-compile
      - name: "ðŸ§ª Java Unit Tests"
        run: ./mvn_cmd test -Dtest=**/*UnitTest -Dsurefire.failIfNoSpecifiedTests=false

  java-approval-tests:
    name: Java Approval Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'
      - name: "Compile"
        run: ./mvn_cmd clean compile test-compile
      - name: "ðŸ“· Java Approval Tests"
        run: ./mvn_cmd test -Dtest=**/*ApprovalTest -Dsurefire.failIfNoSpecifiedTests=false
